# Generated by Django 4.1.5 on 2023-01-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='adani_companies',
        ),
    ]
