# Generated by Django 4.1.5 on 2023-01-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='category',
            field=models.ManyToManyField(related_name='subCategoryColor', to='company.subcategory'),
        ),
    ]
