# Generated by Django 4.1.5 on 2023-01-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
