# Generated by Django 4.1.5 on 2023-01-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_category_options_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.product'),
            preserve_default=False,
        ),
    ]
