# Generated by Django 4.1.5 on 2023-01-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_subcategory_category_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
