# Generated by Django 4.1.5 on 2023-01-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='categories',
        ),
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_fk', to='company.category'),
            preserve_default=False,
        ),
    ]
