# Generated by Django 4.1.5 on 2023-01-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_color_categories_color_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name_plural': 'Product-Price'},
        ),
        migrations.AlterModelTable(
            name='productprice',
            table='company_productPrice',
        ),
    ]
