# Generated by Django 4.1.5 on 2023-01-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_productprice_options_alter_productprice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productprice',
            table='company_product_Price',
        ),
    ]
