# Generated by Django 4.1.5 on 2023-01-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_productprice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='category',
        ),
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.ManyToManyField(related_name='category_m2m', to='company.category'),
        ),
    ]
