# Generated by Django 4.1.5 on 2023-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_productprice_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name_plural': 'Product-Prices'},
        ),
    ]
