# Generated by Django 4.1.5 on 2023-01-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_productprice_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color',
        ),
    ]
